baseURL = 'https://bugtrackhack.me/'
languageCode = 'en-us'
title = 'Welcome'

theme = 'saral'
pygmentsCodefences = true
pygmentsStyle = "doom-one"

[params]
    logoText = "Hii>"
    showHeroImage = true
    isBlogFocused = true
    math = true


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['@@', '@@']]
          inline = [['@', '@']]

